// Generated by CoffeeScript 1.3.3
(function() {
  var CompareAnswer, Fs, Path, cc;

  Fs = require('fs');

  Path = require('path');

  CompareAnswer = (function() {

    function CompareAnswer() {}

    CompareAnswer.prototype.compare = function(answer1, answer2) {
      var c, diff, index, same, _i, _len;
      same = 0;
      diff = 0;
      for (index = _i = 0, _len = answer1.length; _i < _len; index = ++_i) {
        c = answer1[index];
        if (c === answer2[index]) {
          same += 1;
        } else {
          diff += 1;
        }
      }
      return [same, diff];
    };

    CompareAnswer.prototype.filter_no_characters = function(io) {
      var c, s, _i, _len;
      s = "";
      for (_i = 0, _len = io.length; _i < _len; _i++) {
        c = io[_i];
        if (c.match(/[A-Z]/)) {
          s = s + c;
        }
      }
      return s;
    };

    CompareAnswer.prototype.diff = function(fp1, fp2) {
      var data1, data2,
        _this = this;
      data1 = "";
      data2 = "";
      data1 = filter_no_characters(data1);
      data2 = this.filter_no_characters(data2);
      return Fs.readFile(fp1, function(err, data1) {
        if (err) {
          throw err;
        }
        return Fs.readFile(fp2, function(err, data2) {
          if (err) {
            throw err;
          }
        });
      });
    };

    return CompareAnswer;

  })();

  cc = new CompareAnswer;

  console.log(cc.filter_no_characters("1 A 2 B C C"));

  console.log(cc.diff(process.argv[2], process.argv[3]));

}).call(this);
