// Generated by CoffeeScript 1.3.3
(function() {
  var hanoi, i, _i;

  hanoi = function(n, src, aux, dst) {
    if (n > 0) {
      hanoi(n - 1, src, dst, aux);
      console.log("move disc " + n + " from " + src + " to " + dst);
      return hanoi(n - 1, aux, src, dst);
    }
  };

  for (i = _i = 1; _i <= 3; i = ++_i) {
    console.log("#### " + i + " discs");
    hanoi(i, 'SRC', 'AUX', 'DST');
  }

}).call(this);
