// Generated by CoffeeScript 1.3.3
(function() {
  var http, s;

  http = require('http');

  s = http.createServer(function(request, response) {
    response.writeHead(200, {
      'Content-Type': 'text/plain'
    });
    response.end('Hello World\n');
    return console.log(" " + (new Date()) + " a request");
  });

  s.listen(8124);

  http.createServer(function(request, response) {
    response.writeHead(200, {
      'Content-Type': 'text/plain'
    });
    response.end('Hello World\n');
    return console.log(" " + (new Date()) + " a request");
  }).listen(8125);

  http.createServer(function(request, response) {
    response.writeHead(200, {
      'Content-Type': 'text/plain'
    });
    response.end('Hello World\n');
    return console.log((" " + (new Date()) + " a request").listen(8126));
  });

}).call(this);
