// Generated by CoffeeScript 1.3.3
(function() {
  var memoizer;

  memoizer = function(memo, fundamental) {
    var shell;
    shell = function(n) {
      var result;
      result = memo[n];
      if (!(result != null ? result : 'number')) {
        result = fundamental(shell, n);
        memo[n] = result;
      }
      return result;
    };
    return shell;
  };

}).call(this);
