// Generated by CoffeeScript 1.3.3
(function() {
  var a, i, _i, _len;

  a = {
    b: "fadsfaf",
    c: "dfadfdaf"
  };

  for (_i = 0, _len = a.length; _i < _len; _i++) {
    i = a[_i];
    console.log(i);
  }

}).call(this);
